# Site settings
title: Eleutheria
email: eleutheria.network@proton.me
description: > # this means to ignore newlines until "baseurl:"
  KryptoKlubi Eleutheria pyrkii lisäämään tietoisuutta ja osaamista, kasvattamaan/laajentamaan uutta maailmanlaajuista Web 3.0 yhteisöä sekä rakentamaan palveluita uuden verkon päälle käyttäen ilmaisia avoimen lähdekoodin sovelluksia ja lohkoketjuja.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://eleutheria.network" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
